### ISSUE TITLE
Features for initial release

### ISSUE THREAD

**Issue by kiriappeee** [kiriappeee/reply-later#1]
This is to decide what goes into the bare bones release

## Core
- [x] User can be created. The fields required will be a username, auth token, secret token, and default timezone. #2 
  - [x] ~~Only~~ ~~the~~ ~~default~~ ~~timezone~~ ~~can~~ ~~be~~ ~~edited~~ #2   
  * The above got cancelled because it is invalid. Tokens can be reset upon logging in so they too must be updated
- [x] Reply objects can be created #4 
  * Reply objects will have the fields as described in #4 
- [x] User can create a reply to a tweet.
- [x] Replies can be scheduled.
  - [x] Scheduled replies can be different from default timezone
  - [x] The final schedule time will be according to UTC timezone
  - [x] The scheduled replies cannot be prior to the current time. #7
- [x] Replies can be saved #7 
- [x] Saved replies can be retrieved #7 
- [x] Saved replies can be edited #7 
  - [x] Edited replies can also have their timezone and schedule changed
- [x] Saved/scheduled replies can be cancelled #7 
  * Cancelling also requires scheduled cron jobs to be cancelled 
- [x] Messages longer than 140 characters will be broken down #5
  * Broken apart messages must end with a space
  * Each message must have the @ username prefix placed in front of it
  * Each message must reply to the message sent just before it so as to chain the methods together

## Interface
- [x] Users login via twitter (doh) #15 
- [x] Users logging in for the first time will be taken to a screen to select their default timezone #16 (this behaviour is changed slightly. Default timezone will be UTC+00:00. 
- [x] If a user is logging in but has not saved their default timezone (closed browser window last time?) they will be taken to the above mentioned screen.
- [x] The user will then be taken to the main page where they can see two sections: mentions, and schedule #17
- [x] Mentions #17
  - [x] This section will contain a list of mentions (infinitely scrollable, does not auto update). 
  - [x] Clicking on any of the mentions will display another input where the user can reply and schedule the reply
    - [x] The scheduling of the reply will be divided into date, time, am/pm, and timezone. The timezone will default to the user's default timezone
- [x] Schedule #18
  - [x] The user can view the upcoming schedule
  - [x] The user can delete items from the schedule
  - [x] The user will be able to edit. Upon pressing edit, they will be shown an input section like the one where they created a tweet.
- [x] Settings #19
  - [x] The settings will be for the user to edit her default timezone
- [x] Logout. This will take the user to the home page. #20
